### ISSUE TITLE
Link for overriding default parameters in start print is not working

### ISSUE THREAD

**Issue by olofolshall** [boboysdadda/klipper-config#2]
I'm guessing that the URL shorter is expired. Would be super helpful if you could update it. Can't seem to find this info anywhere else.

**Comment by boboysdadda** [comment]
Have you been here? 
https://github.com/KevinOConnor/klipper/blob/master/config/sample-macros.cfg

Or pop in https://discord.gg/df9yTE2 and I'm sure one of us can get you sorted.

**Comment by olofolshall** [comment]
It didn't have any info on overriding the default parameters, I think?
